---
- hosts: users
  become: yes
  vars_files:
    - env_variables
  # vars_prompt:

  #  - name: "username"
  #    prompt: "Account need to be create in remote server."
  #    private: no

  tasks:
    - name: creating the user {{ username }}.
      user:
        name: "{{ username }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        state: present  

    - name: Create a dedicated sudo entry file for the user.
      file:
        path: "/etc/sudoers.d/{{ username }}"
        state: touch
        mode: '0600'

    - name: "Setting up Sudo without Password for user {{ username }}."
      lineinfile:
        dest: "/etc/sudoers.d/{{ username }}"
        line: '{{ username }}  ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set authorized key for user copying it from current {{ username }}  user.
      authorized_key:
         user: "{{ username }}"
         state: present
         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Print the created user.
      shell: id "{{ username }}"
      register: username_created

    - debug:
        msg: "{{ username_created.stdout_lines[0] }}"
...