---
- hosts: kubernetes_master_nodes
  vars_files:
    - env_variables
  remote_user: "{{ username }}"
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
   - name: restart kubectl
     ansible.builtin.systemd:
        name: kubelet
        state: started

   - pause: seconds=30

   - name: Intilizing Kubernetes Cluster
     command: kubeadm init 
     run_once: true

   - pause: seconds=30

   - name: Create directory for kube config.
     become_user: "{{ username }}"
     become_method: sudo
     become: yes
     file: 
       path: /home/{{ username }}/.kube
       state: directory
       owner: "{{ username }}"
       group: "{{ username }}"
       mode: 0755

   - name: Copy /etc/kubernetes/admin.conf to user's home directory /home/{{ username }}/.kube/config.
     become_user: root
     become_method: sudo
     become: yes
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/{{ username }}/.kube/config
       remote_src: yes
       owner: "{{ username }}"
       group: "{{ username }}"
       mode: '0644'

   - pause: seconds=10

   - name: Remove the cache directory.
     become_user: anoni
     become_method: sudo
     become: yes
     file: 
       path: /home/{{ username }}/.kube/cache
       state: absent

   - name: Create Pod Network & RBAC.
     become_user: "{{ username }}"
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items: 
        - kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

   - pause: seconds=30

   - name: Get the token for joining the nodes with Kuberentes master.
     become_user: anoni
     shell: kubeadm token create  --print-join-command
     register: kubernetes_join_command

   - name: Copy join command to local file.
     become_user: anoni
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="./kubernetes_join_command"
...